/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cryptoutils;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {    
        @Test void appHasAGreeting() {
            Hash classUnderTest = new Hash();
            assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        }

}
