/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cryptoutils;

public class CryptoUtils {
    public static String getHash(byte[] message){

        return null;
    }
}
