/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.cryptoutils;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
